### ISSUE TITLE
Rename repo to jvm-redux?

### ISSUE THREAD

**Issue by pardom-zz** [jvm-redux/jvm-redux-api#3]
I think it makes sense for us to provide an official implementation. I think that's also the plan based on our conversations. PR #2 is setup with modules for implementation and Kotlin extensions. Given all this, it seems the name `jvm-redux-api` is now inappropriate.

Thoughts?

**Comment by glung** [comment]
I think it may come later but I don't see it as a priority. 

The priorities to me are : 
- define an API
- define specs
- Implement API and make external stores complies to the specs. 

It see the following benefits to this approach
- This would avoid us to re-implement a store and more importantly re-implement middlewares, enhancers, UIs (like the many dev tools UIs). Avoiding duplicate efforts, **saves time to everybody**. 
- It enables individuals to continue on their project and still benefits from the community. It empowers **collaboration**. 

Note that I am not saying we should not provide any official implementation. But let's not start it already, let's keep the option and review this decision later. (Who knows ? Maybe we could just promote someones store  ?)

What do you think ?

**Comment by beyondeye** [comment]
I am also not convinced that providing a default implementation will help in increasing collaboration between the single developers. At least at this point in time.

**Comment by pardom-zz** [comment]
Makes sense. While we're on the topic of repos, we need to create a middleware API. It doesn't make sense to be in the main API because it's an enhancer implementation.
