### ISSUE TITLE
versioning for jvm-redux-api and reduxjs 4

### ISSUE THREAD

**Issue by beyondeye** [jvm-redux/jvm-redux-api#6]
While we are discussing about defining an api for jvm-redux, reduxjs is actually preparing for the next major release [4.0](https://github.com/reactjs/redux/milestone/3). I think we should add some versioning mechanism for jvm-redux-api to help keep track which version of reduxjs we are referring to and/or some document about which feature are missing vs reduxjs version x

**Comment by glung** [comment]
Yes ! Do you want to rename master 1.x to start with ?

Am 26.10.2016 13:15 schrieb "beyondeye" notifications@github.com:

**Comment by pardom-zz** [comment]
I tagged this before I even saw this, sorry.

https://github.com/jvm-redux/jvm-redux-api/releases/tag/1.0.0
